// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report.proto

/*
Package report is a generated protocol buffer package.

It is generated from these files:
	report.proto

It has these top-level messages:
	ReportRequest
	ReportResponse
	InfoRequest
	ClientInfo
	InfoResponse
*/
package report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ReportRequest describes the request to report in from a client.
type ReportRequest struct {
	Name string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ts   *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=ts" json:"ts,omitempty"`
	Info map[string]string          `protobuf:"bytes,3,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ReportRequest) Reset()                    { *m = ReportRequest{} }
func (m *ReportRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()               {}
func (*ReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReportRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReportRequest) GetTs() *google_protobuf.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *ReportRequest) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

// ReportResponse describes the response from the server when a client reports in.
type ReportResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ReportResponse) Reset()                    { *m = ReportResponse{} }
func (m *ReportResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()               {}
func (*ReportResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReportResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// InfoRequest describes a request to look up info on known clients.
type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// ClientInfo describes info for one client.
type ClientInfo struct {
	Data map[string]string `protobuf:"bytes,1,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ClientInfo) Reset()                    { *m = ClientInfo{} }
func (m *ClientInfo) String() string            { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()               {}
func (*ClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClientInfo) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

// InfoResponse describes a response for info on known clients.
type InfoResponse struct {
	// The info field describes each known client and their info.
	Info map[string]*ClientInfo `protobuf:"bytes,1,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InfoResponse) GetInfo() map[string]*ClientInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*ReportRequest)(nil), "report.ReportRequest")
	proto.RegisterType((*ReportResponse)(nil), "report.ReportResponse")
	proto.RegisterType((*InfoRequest)(nil), "report.InfoRequest")
	proto.RegisterType((*ClientInfo)(nil), "report.ClientInfo")
	proto.RegisterType((*InfoResponse)(nil), "report.InfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Report service

type ReportClient interface {
	// Send report to server.
	Send(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	// Query for info on known clients.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type reportClient struct {
	cc *grpc.ClientConn
}

func NewReportClient(cc *grpc.ClientConn) ReportClient {
	return &reportClient{cc}
}

func (c *reportClient) Send(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := grpc.Invoke(ctx, "/report.Report/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/report.Report/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Report service

type ReportServer interface {
	// Send report to server.
	Send(context.Context, *ReportRequest) (*ReportResponse, error)
	// Query for info on known clients.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterReportServer(s *grpc.Server, srv ReportServer) {
	s.RegisterService(&_Report_serviceDesc, srv)
}

func _Report_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.Report/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).Send(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.Report/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Report_serviceDesc = grpc.ServiceDesc{
	ServiceName: "report.Report",
	HandlerType: (*ReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Report_Send_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Report_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}

func init() { proto.RegisterFile("report.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xd1, 0x4e, 0xf2, 0x30,
	0x14, 0xc7, 0xe9, 0xd8, 0xc7, 0x17, 0xce, 0xe0, 0xcb, 0x97, 0x8a, 0x66, 0x59, 0x8c, 0x90, 0xc5,
	0x8b, 0x85, 0x8b, 0x62, 0xc6, 0x05, 0xc6, 0x4b, 0xd4, 0x0b, 0xe3, 0x8d, 0x99, 0xbe, 0x40, 0x09,
	0x05, 0x11, 0xd6, 0xce, 0xb5, 0x60, 0x78, 0x0a, 0x9f, 0xc8, 0x77, 0x33, 0x6b, 0x57, 0x04, 0x21,
	0x26, 0xde, 0xf5, 0x9c, 0xfd, 0x77, 0xfe, 0xbf, 0xf3, 0x6f, 0xa1, 0x91, 0xb3, 0x4c, 0xe4, 0x8a,
	0x64, 0xb9, 0x50, 0x02, 0xd7, 0x4c, 0x15, 0xb4, 0xa7, 0x42, 0x4c, 0x17, 0xac, 0xa7, 0xbb, 0xa3,
	0xe5, 0xa4, 0xa7, 0x66, 0x29, 0x93, 0x8a, 0xa6, 0x99, 0x11, 0x86, 0x1f, 0x08, 0x9a, 0x89, 0xd6,
	0x26, 0xec, 0x75, 0xc9, 0xa4, 0xc2, 0x18, 0x5c, 0x4e, 0x53, 0xe6, 0xa3, 0x0e, 0x8a, 0xea, 0x89,
	0x3e, 0xe3, 0x2e, 0x38, 0x4a, 0xfa, 0x4e, 0x07, 0x45, 0x5e, 0x1c, 0x10, 0x33, 0x93, 0xd8, 0x99,
	0xe4, 0xc9, 0xce, 0x4c, 0x1c, 0x25, 0x71, 0x1f, 0xdc, 0x19, 0x9f, 0x08, 0xbf, 0xda, 0xa9, 0x46,
	0x5e, 0xdc, 0x26, 0x25, 0xd7, 0x8e, 0x09, 0xb9, 0xe3, 0x13, 0x71, 0xcb, 0x55, 0xbe, 0x4e, 0xb4,
	0x38, 0x18, 0x40, 0x7d, 0xd3, 0xc2, 0xff, 0xa1, 0x3a, 0x67, 0xeb, 0x12, 0xa0, 0x38, 0xe2, 0x16,
	0xfc, 0x59, 0xd1, 0xc5, 0x92, 0x69, 0x84, 0x7a, 0x62, 0x8a, 0x2b, 0xe7, 0x12, 0x85, 0x5d, 0xf8,
	0x67, 0x27, 0xcb, 0x4c, 0x70, 0xc9, 0xb0, 0x0f, 0x7f, 0x53, 0x26, 0x25, 0x9d, 0xda, 0x15, 0x6c,
	0x19, 0x36, 0xc1, 0x2b, 0x4c, 0x4a, 0x86, 0xf0, 0x0d, 0xe0, 0x7a, 0x31, 0x63, 0x5c, 0x15, 0x4d,
	0x7c, 0x01, 0xee, 0x98, 0x2a, 0xea, 0x23, 0x8d, 0x7d, 0x6a, 0xb1, 0xbf, 0x14, 0xe4, 0x86, 0x2a,
	0x5a, 0x32, 0x17, 0xca, 0x82, 0x79, 0xd3, 0xfa, 0x15, 0xf3, 0x3b, 0x82, 0x86, 0x01, 0x29, 0x91,
	0xe3, 0x32, 0x32, 0xe3, 0x7d, 0x66, 0xbd, 0xb7, 0x35, 0x7b, 0x89, 0xdd, 0xff, 0x9c, 0x58, 0xb4,
	0xed, 0xee, 0xc5, 0x78, 0x7f, 0x9f, 0x2d, 0xa2, 0x78, 0x05, 0x35, 0x93, 0x22, 0x1e, 0x80, 0xfb,
	0xc8, 0xf8, 0x18, 0x1f, 0x1f, 0xbc, 0xb7, 0xe0, 0xe4, 0x7b, 0xdb, 0xd0, 0x85, 0x95, 0xe2, 0xda,
	0x75, 0x8e, 0x47, 0xbb, 0xf4, 0xe6, 0xb7, 0xd6, 0xa1, 0x95, 0xc2, 0xca, 0xf0, 0x1c, 0xfc, 0x94,
	0x91, 0xe7, 0xf9, 0x0b, 0x37, 0xaf, 0x49, 0x15, 0x6f, 0xc3, 0x48, 0x87, 0x25, 0xd1, 0x03, 0x1a,
	0xd5, 0xf4, 0xb7, 0xfe, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0x77, 0x08, 0xa6, 0xe3, 0x02,
	0x00, 0x00,
}
