image: golang
script:
  # TODO: Find a way around having to manually add hkjn.me/timeutils
  # dependency (it doesn't get pulled in because only *_test.go files
  # import it).
  - go get -v hkjn.me/timeutils hkjn.me/junk/...
  - go build -v ./...
  - go test -v ./...
notify:
  email:
    recipients:
      - henrik+drone@safello.com
# TODO: SSH'ing to a produciton server and deploying might look like this:
#  ssh:
#    target: user@test.example.com:/srv/app/location 2212
#    artifacts:
#      - build.result
#      - config/file
#    cmd: /opt/bin/redeploy.sh
# TODO: Auto-deploying when tests pass might look like this:
# deploy:
#    bash:
#        script:
#          - ./bin/prepare_for_deploy.sh
#          - ./bin/make_deploy.sh
#          - ./bin/finish_deploy.sh
# TODO: 'publish' section could be used to automatically rebuild Docker images here:
# http://drone.readthedocs.org/en/stable/publish.html
# publish:
#    docker:
#        docker_host: tcp://docker.example.com:1000
#        docker_version: 1.0
#        registry_login: false
#        image_name: docker.example.com/my-webapp
#        keep_builds: false
#        tag: 0.1
# TODO: Could also do a Github release..