language: generic
sudo: required
services:
  - docker
install:
  - sudo pip install https://github.com/goldmann/docker-squash/archive/master.zip
  # On 1. day, still use last month's tarfile,
  # the latest one may not be on the mirror yet
  - ./download yesterday
script:
  - sudo ./build
  - ./tag
after_success:
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./push'
