#!/usr/bin/env bash

set -euo pipefail

declare BASE_IMAGE="hkjn/golang:$(uname -m)"
declare BUILD_DIR="$(mktemp -d)"

echo "Building in $BASE_IMAGE.."
sed "s|{{ARG_FROM}}|${BASE_IMAGE}|g" Dockerfile.build > $BUILD_DIR/Dockerfile
cp -r {client,server,report,vendor} $BUILD_DIR
docker build -t repotest-build $BUILD_DIR
docker run --name repotest-build repotest-build
docker cp repotest-build:/home/go/bin/ $(pwd)
docker rm repotest-build
mv -iv bin/* .
