#cloud-config
coreos:
  fleet:
    metadata: stage=test
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/8892f376c6597e36976aacbbe0d6dad0
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  units:
    # we want to start etcd and fleet on all VMs.
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start